# Generated by Django 5.2.1 on 2025-06-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
        migrations.AddField(
            model_name='article',
            name='commentaire',
            field=models.CharField(default='', max_length=100),
        ),
    ]
