# Generated by Django 5.2.1 on 2025-06-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_categorie_article_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.CharField(default='', max_length=100),
        ),
    ]
